export default {
    GET_USERS:'GET_USERS',
    GET_USERS_SUCCESS:'GET_USERS_SUCCESS',
    GET_USERS_FAILED:'GET_USERS_FAILED',
    ADD_USER:'ADD_USER',
    ADD_USER_SUCCESS:'ADD_USER_SUCCESS',
    ADD_USER_FAILED:'ADD_USER_FAILED',
    EDIT_USER:'EDIT_USER',
    EDIT_USER_SUCCESS:'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED:'EDIT_USER_FAILED'
}